<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_GoToHomepage</name>
   <tag></tag>
   <elementGuidId>3000eda8-a5f9-4c38-b5b4-1fe80a259612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;summary&quot;]/div/div/div[7]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;summary&quot;]/div/div/div[7]/p/a</value>
      <webElementGuid>919b5292-b009-48be-8251-cfaefdd79ea6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
