<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_AppointmentConfirmation</name>
   <tag></tag>
   <elementGuidId>052a20c4-477f-4fcf-997b-c1ba6b1dd4c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;summary&quot;]/div/div/div[1]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;summary&quot;]/div/div/div[1]/h2</value>
      <webElementGuid>ceee0951-9c44-4e97-be03-5c1152d8677e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
