<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>humberger-history</name>
   <tag></tag>
   <elementGuidId>6ccc3df2-bd40-4148-a20a-34fdb3b067f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidebar-wrapper&quot;]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-wrapper&quot;]/ul/li[3]/a</value>
      <webElementGuid>47bbed38-af72-47ec-8d75-593c088b04e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
