<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>humberger-home</name>
   <tag></tag>
   <elementGuidId>64720878-6698-4045-8e13-366458413764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-wrapper&quot;]/ul/li[2]/a</value>
      <webElementGuid>1ce0f3b8-9d41-4b4c-9d1e-f9310994c9d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
